import { describe, it, expect } from 'vitest'
import { makeBeamGreedy, BEAM_REPLY_LIMITS } from '../ai/greedyAi'
import { DEFAULT_WEIGHTS } from '../ai/evaluate'
import { effectiveCost } from '../engine/legalMoves'
import type { GameState } from '../engine/types'
import { state, player, card, ready, CARDS } from './helpers/engineFixtures'
import '../engine/cardDefinitions'

/**
 * Does declining a resource ever pay? (#519)
 *
 * ## Why a scripted position rather than a rate
 *
 * The A/B answers "is it harmful" and answers it well: the driver alone measures **-3.52** over 2016
 * games, and with the deploy gate on top the arm measures **-0.30**, indistinguishable from the
 * shipped bot. What self-play cannot answer is whether declining ever *pays*, for two reasons that are
 * both properties of the corpus rather than of the rule.
 *
 * The bench corpus is generated by the bots themselves, so a position that arises mainly against an
 * opponent who punishes a starved board never occurs. And an effect worth a point would need roughly
 * 10,000 games an arm to separate from zero, where 2,000 buys an interval of about +/-2.3.
 *
 * So the question is settled the way the shielded-Sentinel lockout and `hand.canAct` were: build the
 * position the rule describes, and let the two bots decide it. Two calls rather than 20,000 games.
 *
 * ## The property that makes the position decidable
 *
 * A resource is worth having only if it buys something. **Below** the total cost of the hand, another
 * resource buys reach: it brings a card into range. **Above** it, the next resource buys nothing at
 * all, because there is nothing left to spend it on, while the card it costs still converts into a
 * body.
 *
 * That is the whole of the claim, and it is checkable rather than a matter of taste: the position
 * asserts `pool >= total hand cost` explicitly, so "the resource cannot be spent" is a fact about the
 * board and not an opinion about the weights. Every position below is built from that property, never
 * from a number chosen because it produced the answer wanted.
 */

const L = {
  ...CARDS,
  LEADER: card({ id: 'LEADER', type: 'leader', cost: 5, power: 4, hp: 7, aspects: ['Command', 'Heroism'] }),
  // Three bodies a full pool can deploy in one round. Cheap on purpose: the point is that the hand is
  // entirely affordable, so an extra resource is dead weight while every card is still live.
  SMALL: card({ id: 'SMALL', type: 'unit', arena: 'ground', cost: 2, power: 2, hp: 2, aspects: ['Command'], rarity: 'Common' }),
  MID: card({ id: 'MID', type: 'unit', arena: 'ground', cost: 3, power: 3, hp: 3, aspects: ['Command'], rarity: 'Common' }),
}

/** The candidate: the driver plus its guard rail, at the cell measured at -0.30 over 2016 games. */
const GATED = { ...DEFAULT_WEIGHTS, cardScarcity: 3, handKnee: 3, deployUrgency: 2 }

/**
 * The control, stated explicitly rather than taken from the shipped defaults. The shipped bot now
 * carries `cardScarcity`, so reading it as the term-off arm would silently compare the term with
 * itself and report no difference.
 */
const UNGATED = { ...DEFAULT_WEIGHTS, cardScarcity: 0 }

const shipped = makeBeamGreedy(DEFAULT_WEIGHTS, BEAM_REPLY_LIMITS)
const gated = makeBeamGreedy(GATED, BEAM_REPLY_LIMITS)
const ungated = makeBeamGreedy(UNGATED, BEAM_REPLY_LIMITS)

/**
 * A regroup with a given pool and hand, and the leader already deployed unless asked otherwise.
 *
 * The leader matters because the deploy gate deliberately overrides everything else while it is still
 * in the base zone: "keep resourcing until you can deploy your leader" is the one rule allowed to
 * outrank a full pool.
 */
function regroup(pool: number, hand: string[], leaderDeployed = true): GameState {
  return state({
    phase: 'regroup',
    activePlayer: 'player',
    cards: L,
    players: {
      player: player({
        leader: { cardId: 'LEADER', deployed: leaderDeployed, epicActionUsed: leaderDeployed, exhausted: false },
        hand,
        resources: ready(pool),
      }),
      opponent: player({ leader: { cardId: 'LEADER', deployed: true, epicActionUsed: true, exhausted: false } }),
    },
  })
}

const handCost = (s: GameState): number =>
  s.players.player.hand.reduce((n, id) => n + effectiveCost(s, 'player', s.cards[id]), 0)

const banks = (ai: typeof shipped, s: GameState): boolean => ai(s)?.type === 'resourceCard'

describe('the position where a resource buys nothing', () => {
  // Pool 8 against a hand costing 8: everything held is castable next round with nothing left over,
  // so the ninth resource is unspendable and the card it costs is not.
  const saturated = regroup(8, ['SMALL', 'MID', 'MID'])

  it('is built from the property, not from a number that happened to work', () => {
    expect(handCost(saturated), 'the whole hand is affordable from the pool as it stands')
      .toBeLessThanOrEqual(saturated.players.player.resources.length)
    expect(saturated.players.player.hand.length, 'and there is a real choice of card to give up')
      .toBeGreaterThan(1)
  })

  /**
   * Without the scarcity bonus, `resource - card` is a constant +2, so this position is decided
   * identically to a round-one position with two resources and a full hand. It is not a judgement; it
   * is the same answer everywhere, and that constancy is what the bonus exists to break.
   */
  it('a bot without the bonus banks anyway, because its answer never depends on the board', () => {
    expect(banks(ungated, saturated)).toBe(true)
  })

  it('the shipped bot declines, now that it carries the bonus', () => {
    expect(banks(shipped, saturated)).toBe(false)
  })

  it('the gated bot declines', () => {
    expect(banks(gated, saturated)).toBe(false)
  })
})

/**
 * The other half, and the one that decides whether the rule is safe rather than merely clever.
 *
 * Declining early is what the ungated driver did and what cost it 3.52 points: it skipped 0.4% of
 * round-one regroups and 8.3% of round-four ones, starving itself of the pool it needed. Both bots
 * must bank in every position where the resource still buys something.
 */
describe('the positions where a resource still buys something', () => {
  it('banks from a full hand it cannot yet afford', () => {
    const early = regroup(2, ['SMALL', 'MID', 'MID', 'MID', 'SMALL'])
    expect(handCost(early), 'the pool cannot cast the hand, so reach is still worth buying')
      .toBeGreaterThan(early.players.player.resources.length)
    expect(banks(shipped, early)).toBe(true)
    expect(banks(gated, early)).toBe(true)
  })

  /**
   * A small hand does NOT mean decline. With the pool short of the hand's cost the extra resource
   * still buys reach, and the gate must not fire on hand size alone.
   */
  it('banks from a small but unaffordable hand', () => {
    const short = regroup(2, ['MID', 'MID', 'MID'])
    expect(handCost(short)).toBeGreaterThan(short.players.player.resources.length)
    expect(banks(gated, short)).toBe(true)
  })

  /**
   * The deploy gate outranks a saturated pool. This is the same board as the decidable position above
   * except that the leader is still in the base zone, and "keep resourcing until you can deploy your
   * leader" is a resource COUNT (CR 2.6.1), so it wins.
   */
  it('banks while the leader is still undeployed, saturated pool or not', () => {
    const undeployed = regroup(4, ['SMALL', 'MID', 'MID'], false)
    expect(banks(gated, undeployed)).toBe(true)
  })
})
