import { describe, it, expect } from 'vitest'
import ashSet from './fixtures/ashSet.json'
import type { SwuCard } from '../data/cards'
import { bundledCanonicalId } from '../data/bundledPrintings'
import ashPrintingMap from '../data/printingMaps/ash.json'

/**
 * The bundled printing map (#389): every ASH printing (Normal, Hyperspace, foil, prestige,
 * showcase…) mapped to its Normal id ahead of time, generated by `scripts/generatePrintingMap.mjs`
 * from the full `/cards/ASH` listing (925 rows) rather than the Normal-only `search` listing (264).
 * This is what lets a known card resolve instantly and offline, with no IndexedDB/network race:
 * the actual mechanism behind #389, where an incomplete browser cache silently short-circuited the
 * dynamic fallback before it ever reached the network.
 *
 * These tests pin the checked-in file's invariants against the checked-in `ashSet.json` fixture
 * (264 Normal cards), so a bad regeneration is caught without any network access in CI.
 */

const ASH_NORMAL_IDS = new Set((ashSet as unknown as SwuCard[]).map(c => `${c.Set}_${c.Number}`))
const map = ashPrintingMap as Record<string, string>

describe('bundled ASH printing map', () => {
  it('has one entry per known ASH printing (925: 264 Normal + 661 variants)', () => {
    expect(Object.keys(map)).toHaveLength(925)
  })

  it('maps every id to a real Normal id from the fixture', () => {
    for (const [id, normalId] of Object.entries(map)) {
      expect(ASH_NORMAL_IDS.has(normalId), `${id} -> ${normalId}`).toBe(true)
    }
  })

  it('maps every Normal id to itself', () => {
    for (const id of ASH_NORMAL_IDS) {
      expect(map[id], id).toBe(id)
    }
  })

  it('resolves the printings from #389 to their Normal ids', () => {
    expect(map.ASH_308).toBe('ASH_044') // Barriss Offee, Hyperspace
    expect(map.ASH_546).toBe('ASH_044') // Barriss Offee, Hyperspace Foil
    expect(map.ASH_344).toBe('ASH_080') // Covert Believers, Hyperspace
  })
})

describe('bundledCanonicalId', () => {
  it('resolves a bundled id', () => {
    expect(bundledCanonicalId('ASH_308')).toBe('ASH_044')
  })

  it('returns undefined for an id that is not bundled', () => {
    expect(bundledCanonicalId('ZZZ_001')).toBeUndefined()
  })
})
