// Generate `src/buildIdentity.ts`: the two identifiers the app and the bench need (#480).
//
// This file is GITIGNORED. That is the point rather than a convenience: the previous `BUILD_TAG` was
// a tracked counter bumped on every `npm run check`, so two branches issued the same number to
// different code (b446 went to two commits, with no merge involved) and every merge conflicted on it.
// An untracked file cannot do either.
//
// Two identifiers, two audiences:
//   COMMIT_ID  machine-facing, git-derived, unique by construction. Stamped on bench runs so a
//              measurement is attributable to real code.
//   RELEASE    human-facing, issued once by the pipeline so it cannot collide. Quoted in support.
//
// In CI both come from the environment, which also sidesteps the shallow clone: `actions/checkout`
// defaults to `fetch-depth: 1`, so anything derived from history would be wrong, while `rev-parse`
// works at depth 1 and `run_number` needs no history at all.
import { writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

const git = (...args) => {
  try {
    return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
  } catch {
    return ''
  }
}

/**
 * A tree with uncommitted changes cannot be attributed to any commit, and most AI measurement happens
 * exactly there. Marking it is what stops a dirty run being read as a clean one.
 */
const isDirty = () => git('status', '--porcelain') !== ''

function identity() {
  // GitHub Actions sets both for every step, so CI needs no workflow changes.
  const sha = process.env.GITHUB_SHA
  const run = process.env.GITHUB_RUN_NUMBER
  if (sha) {
    return { commit: sha.slice(0, 7), release: run ?? `ci-${sha.slice(0, 7)}` }
  }

  const local = git('rev-parse', '--short', 'HEAD') || 'unknown'
  const commit = isDirty() ? `${local}-dirty` : local
  // No release number exists locally, and a local build must never look like one.
  return { commit, release: `dev-${local}` }
}

const { commit, release } = identity()
const path = new URL('../src/buildIdentity.ts', import.meta.url)

writeFileSync(path, `// GENERATED by scripts/buildIdentity.mjs. Not tracked: see #480.
/** Machine-facing. Git-derived and unique, so a bench measurement is attributable to real code.
 *  A \`-dirty\` suffix means the tree had uncommitted changes and the run belongs to no commit. */
export const COMMIT_ID = '${commit}'

/** Human-facing. Issued by the deployment pipeline, so it is monotonic and cannot collide.
 *  Local builds carry a \`dev-\` marker instead, because they are not releases. */
export const RELEASE = '${release}'
`)

console.log(`build identity → commit ${commit}, release ${release}`)
